using Snowflake.Configuration;
using Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration;
using Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal;

namespace Snowflake.Plugin.EmulatorHandler.RetroArch
{
    //autogenerated using generate_retroarch.py
    public partial class RetroArchConfiguration : ConfigurationCollection
    {
        public BuiltinConfiguration BuiltinConfiguration => this.Get<BuiltinConfiguration>("builtin");
        public MenuConfiguration MenuConfiguration => this.Get<MenuConfiguration>("menu");
        public GameConfiguration GameConfiguration => this.Get<GameConfiguration>("game");
        public RecordConfiguration RecordConfiguration => this.Get<RecordConfiguration>("record");
        public PauseConfiguration PauseConfiguration => this.Get<PauseConfiguration>("pause");
        public LocationConfiguration LocationConfiguration => this.Get<LocationConfiguration>("location");
        public NetworkConfiguration NetworkConfiguration => this.Get<NetworkConfiguration>("network");
        public LogConfiguration LogConfiguration => this.Get<LogConfiguration>("log");
        public InputConfiguration InputConfiguration => this.Get<InputConfiguration>("input");
        public NetplayConfiguration NetplayConfiguration => this.Get<NetplayConfiguration>("netplay");
        public XmbConfiguration XmbConfiguration => this.Get<XmbConfiguration>("xmb");
        public StdinConfiguration StdinConfiguration => this.Get<StdinConfiguration>("stdin");
        public CoreConfiguration CoreConfiguration => this.Get<CoreConfiguration>("core");
        public CameraConfiguration CameraConfiguration => this.Get<CameraConfiguration>("camera");
        public BundleConfiguration BundleConfiguration => this.Get<BundleConfiguration>("bundle");

        public RewindConfiguration RewindConfiguration => this.Get<RewindConfiguration>("rewind");

        public SaveConfiguration SaveConfiguration => this.Get<SaveConfiguration>("save");
        public UserConfiguration UserConfiguration => this.Get<UserConfiguration>("user");

        public ThreadedConfiguration ThreadedConfiguration => this.Get<ThreadedConfiguration>("threaded");
        public DirectoryConfiguration DirectoryConfiguration => this.Get<DirectoryConfiguration>("directory");
        public UiConfiguration UiConfiguration => this.Get<UiConfiguration>("ui");

    }
}

