codecov:
  branch: master       # the branch to show by default, inherited from your git repository settings
  strict_yaml_branch: master
  ci:
    - !codefactor.io
    - !www.codefactor.io
coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    project:
      default:
        target: auto
        if_no_uploads: error
        set_pending: yes
        if_no_uploads: error
    patch:
      default:
        if_no_uploads: error
        target: '50'
        set_pending: yes
fixes:
  - "build/::"
comment:
  layout: "header, diff, changes, suggestions, sunburst"
  behavior: default
