codecov:
  branch: master       # the branch to show by default, inherited from your git repository settings
coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error
        target: '50'

    changes: true
comment:
  layout: "header, diff, changes, suggestions, sunburst"
  behavior: default
