using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Snowflake.Emulator.Input.Constants
{
    public static class KeyboardConstants
    {
        public static readonly string KEY_A = "KEY_A";
        public static readonly string KEY_B = "KEY_B";
        public static readonly string KEY_C = "KEY_C";
        public static readonly string KEY_D = "KEY_D";
        public static readonly string KEY_E = "KEY_E";
        public static readonly string KEY_F = "KEY_F";
        public static readonly string KEY_G = "KEY_G";
        public static readonly string KEY_H = "KEY_H";
        public static readonly string KEY_I = "KEY_I";
        public static readonly string KEY_J = "KEY_J";
        public static readonly string KEY_K = "KEY_K";
        public static readonly string KEY_L = "KEY_L";
        public static readonly string KEY_M = "KEY_M";
        public static readonly string KEY_N = "KEY_N";
        public static readonly string KEY_O = "KEY_O";
        public static readonly string KEY_P = "KEY_P";
        public static readonly string KEY_Q = "KEY_Q";
        public static readonly string KEY_R = "KEY_R";
        public static readonly string KEY_S = "KEY_S";
        public static readonly string KEY_T = "KEY_T";
        public static readonly string KEY_U = "KEY_U";
        public static readonly string KEY_V = "KEY_V";
        public static readonly string KEY_W = "KEY_W";
        public static readonly string KEY_X = "KEY_X";
        public static readonly string KEY_Y = "KEY_Y";
        public static readonly string KEY_Z = "KEY_Z";
        public static readonly string KEY_0 = "KEY_0";
        public static readonly string KEY_1 = "KEY_1";
        public static readonly string KEY_2 = "KEY_2";
        public static readonly string KEY_3 = "KEY_3";
        public static readonly string KEY_4 = "KEY_4";
        public static readonly string KEY_5 = "KEY_5";
        public static readonly string KEY_6 = "KEY_6";
        public static readonly string KEY_7 = "KEY_7";
        public static readonly string KEY_8 = "KEY_8";
        public static readonly string KEY_9 = "KEY_9";
        public static readonly string KEY_EQUALS = "KEY_EQUALS";
        public static readonly string KEY_MINUS = "KEY_MINUS";
        public static readonly string KEY_BACKSPACE = "KEY_BACKSPACE";
        public static readonly string KEY_SPACEBAR = "KEY_SPACEBAR";
        public static readonly string KEY_ENTER = "KEY_ENTER";
        public static readonly string KEY_UP = "KEY_UP";
        public static readonly string KEY_DOWN = "KEY_DOWN";
        public static readonly string KEY_LEFT = "KEY_LEFT";
        public static readonly string KEY_RIGHT = "KEY_RIGHT";
        public static readonly string KEY_TAB = "KEY_TAB";
        public static readonly string KEY_INSERT = "KEY_INSERT";
        public static readonly string KEY_DELETE = "KEY_DELETE";
        public static readonly string KEY_HOME = "KEY_HOME";
        public static readonly string KEY_END = "KEY_END";
        public static readonly string KEY_PAGE_UP = "KEY_PAGE_UP";
        public static readonly string KEY_PAGE_DOWN = "KEY_PAGE_DOWN";
        public static readonly string KEY_SHIFT = "KEY_SHIFT";
        public static readonly string KEY_CTRL = "KEY_CTRL";
        public static readonly string KEY_ALT = "KEY_ALT";
        public static readonly string KEY_ESCAPE = "KEY_ESCAPE";
        public static readonly string KEY_TILDE = "KEY_TILDE";
        public static readonly string KEY_QUOTE = "KEY_QUOTE";
        public static readonly string KEY_SEMICOLON = "KEY_SEMICOLON";
        public static readonly string KEY_COMMA = "KEY_COMMA";
        public static readonly string KEY_PERIOD = "KEY_PERIOD";
        public static readonly string KEY_SLASH = "KEY_SLASH";
        public static readonly string KEY_BRACKET_LEFT = "KEY_BRACKET_LEFT";
        public static readonly string KEY_BRACKET_RIGHT = "KEY_BRACKET_RIGHT";
        public static readonly string KEY_BACKSLASH = "KEY_BACKSLASH";
        public static readonly string KEY_RIGHT_ALT = "KEY_RIGHT_ALT";
        public static readonly string KEY_RIGHT_CTRL = "KEY_RIGHT_CTRL";
        public static readonly string KEY_RIGHT_SHIFT = "KEY_RIGHT_SHIFT";
        public static readonly string KEY_NUMPAD_0 = "KEY_NUMPAD_0";
        public static readonly string KEY_NUMPAD_1 = "KEY_NUMPAD_1";
        public static readonly string KEY_NUMPAD_2 = "KEY_NUMPAD_2";
        public static readonly string KEY_NUMPAD_3 = "KEY_NUMPAD_3";
        public static readonly string KEY_NUMPAD_4 = "KEY_NUMPAD_4";
        public static readonly string KEY_NUMPAD_5 = "KEY_NUMPAD_5";
        public static readonly string KEY_NUMPAD_6 = "KEY_NUMPAD_6";
        public static readonly string KEY_NUMPAD_7 = "KEY_NUMPAD_7";
        public static readonly string KEY_NUMPAD_8 = "KEY_NUMPAD_8";
        public static readonly string KEY_NUMPAD_9 = "KEY_NUMPAD_9";
        public static readonly string KEY_NUMPAD_PERIOD = "KEY_NUMPAD_PERIOD";
        public static readonly string KEY_NUMPAD_PLUS = "KEY_NUMPAD_PLUS";
        public static readonly string KEY_NUMPAD_MINUS = "KEY_NUMPAD_MINUS";
        public static readonly string KEY_NUMPAD_ENTER = "KEY_NUMPAD_ENTER";
        public static readonly string KEY_F_1 = "KEY_F_1";
        public static readonly string KEY_F_2 = "KEY_F_2";
        public static readonly string KEY_F_3 = "KEY_F_3";
        public static readonly string KEY_F_4 = "KEY_F_4";
        public static readonly string KEY_F_5 = "KEY_F_5";
        public static readonly string KEY_F_6 = "KEY_F_6";
        public static readonly string KEY_F_7 = "KEY_F_7";
        public static readonly string KEY_F_8 = "KEY_F_8";
        public static readonly string KEY_F_9 = "KEY_F_9";
        public static readonly string KEY_F_10 = "KEY_F_10";
        public static readonly string KEY_F_11 = "KEY_F_11";
        public static readonly string KEY_F_12 = "KEY_F_12";
    }
}
