using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration
{
    public class PauseConfiguration : ConfigurationSection
    {

        [ConfigurationOption("pause_nonactive", DisplayName = "Pause when not in focus")]
        public bool PauseNonactive { get; set; } = true;

        public PauseConfiguration() : base("pause", "Pause Options")
        {

        }

    }
}
