using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Snowflake.Emulator.Core.Mapping
{
    public class KeyboardMapping
    {
        public readonly string KEY_A;
        public readonly string KEY_B;
        public readonly string KEY_C;
        public readonly string KEY_D;
        public readonly string KEY_E;
        public readonly string KEY_F;
        public readonly string KEY_G;
        public readonly string KEY_H;
        public readonly string KEY_I;
        public readonly string KEY_J;
        public readonly string KEY_K;
        public readonly string KEY_L;
        public readonly string KEY_M;
        public readonly string KEY_N;
        public readonly string KEY_O;
        public readonly string KEY_P;
        public readonly string KEY_Q;
        public readonly string KEY_R;
        public readonly string KEY_S;
        public readonly string KEY_T;
        public readonly string KEY_U;
        public readonly string KEY_V;
        public readonly string KEY_W;
        public readonly string KEY_X;
        public readonly string KEY_Y;
        public readonly string KEY_Z;
        public readonly string KEY_0;
        public readonly string KEY_1;
        public readonly string KEY_2;
        public readonly string KEY_3;
        public readonly string KEY_4;
        public readonly string KEY_5;
        public readonly string KEY_6;
        public readonly string KEY_7;
        public readonly string KEY_8;
        public readonly string KEY_9;
        public readonly string KEY_EQUALS;
        public readonly string KEY_MINUS;
        public readonly string KEY_BACKSPACE;
        public readonly string KEY_SPACEBAR;
        public readonly string KEY_ENTER;
        public readonly string KEY_UP;
        public readonly string KEY_DOWN;
        public readonly string KEY_LEFT;
        public readonly string KEY_RIGHT;
        public readonly string KEY_TAB;
        public readonly string KEY_INSERT;
        public readonly string KEY_DELETE;
        public readonly string KEY_HOME;
        public readonly string KEY_END;
        public readonly string KEY_PAGE_UP;
        public readonly string KEY_PAGE_DOWN;
        public readonly string KEY_SHIFT;
        public readonly string KEY_CTRL;
        public readonly string KEY_ALT;
        public readonly string KEY_ESCAPE;
        public readonly string KEY_TILDE;
        public readonly string KEY_QUOTE;
        public readonly string KEY_SEMICOLON;
        public readonly string KEY_COMMA;
        public readonly string KEY_PERIOD;
        public readonly string KEY_SLASH;
        public readonly string KEY_BRACKET_LEFT;
        public readonly string KEY_BRACKET_RIGHT;
        public readonly string KEY_BACKSLASH;
        public readonly string KEY_RIGHT_ALT;
        public readonly string KEY_RIGHT_CTRL;
        public readonly string KEY_RIGHT_SHIFT;
        public readonly string KEY_NUMPAD_0;
        public readonly string KEY_NUMPAD_1;
        public readonly string KEY_NUMPAD_2;
        public readonly string KEY_NUMPAD_3;
        public readonly string KEY_NUMPAD_4;
        public readonly string KEY_NUMPAD_5;
        public readonly string KEY_NUMPAD_6;
        public readonly string KEY_NUMPAD_7;
        public readonly string KEY_NUMPAD_8;
        public readonly string KEY_NUMPAD_9;
        public readonly string KEY_NUMPAD_PERIOD;
        public readonly string KEY_NUMPAD_PLUS;
        public readonly string KEY_NUMPAD_MINUS;
        public readonly string KEY_NUMPAD_ENTER;
        public readonly string KEY_F_1;
        public readonly string KEY_F_2;
        public readonly string KEY_F_3;
        public readonly string KEY_F_4;
        public readonly string KEY_F_5;
        public readonly string KEY_F_6;
        public readonly string KEY_F_7;
        public readonly string KEY_F_8;
        public readonly string KEY_F_9;
        public readonly string KEY_F_10;
        public readonly string KEY_F_11;
        public readonly string KEY_F_12;

        public KeyboardMapping(IDictionary<string, string> mappingData)
        {
            this.KEY_A = mappingData["KEY_A"];
            this.KEY_B = mappingData["KEY_B"];
            this.KEY_C = mappingData["KEY_C"];
            this.KEY_D = mappingData["KEY_D"];
            this.KEY_E = mappingData["KEY_E"];
            this.KEY_F = mappingData["KEY_F"];
            this.KEY_G = mappingData["KEY_G"];
            this.KEY_H = mappingData["KEY_H"];
            this.KEY_I = mappingData["KEY_I"];
            this.KEY_J = mappingData["KEY_J"];
            this.KEY_K = mappingData["KEY_K"];
            this.KEY_L = mappingData["KEY_L"];
            this.KEY_M = mappingData["KEY_M"];
            this.KEY_N = mappingData["KEY_N"];
            this.KEY_O = mappingData["KEY_O"];
            this.KEY_P = mappingData["KEY_P"];
            this.KEY_Q = mappingData["KEY_Q"];
            this.KEY_R = mappingData["KEY_R"];
            this.KEY_S = mappingData["KEY_S"];
            this.KEY_T = mappingData["KEY_T"];
            this.KEY_U = mappingData["KEY_U"];
            this.KEY_V = mappingData["KEY_V"];
            this.KEY_W = mappingData["KEY_W"];
            this.KEY_X = mappingData["KEY_X"];
            this.KEY_Y = mappingData["KEY_Y"];
            this.KEY_Z = mappingData["KEY_Z"];
            this.KEY_0 = mappingData["KEY_0"];
            this.KEY_1 = mappingData["KEY_1"];
            this.KEY_2 = mappingData["KEY_2"];
            this.KEY_3 = mappingData["KEY_3"];
            this.KEY_4 = mappingData["KEY_4"];
            this.KEY_5 = mappingData["KEY_5"];
            this.KEY_6 = mappingData["KEY_6"];
            this.KEY_7 = mappingData["KEY_7"];
            this.KEY_8 = mappingData["KEY_8"];
            this.KEY_9 = mappingData["KEY_9"];
            this.KEY_EQUALS = mappingData["KEY_EQUALS"];
            this.KEY_MINUS = mappingData["KEY_MINUS"];
            this.KEY_BACKSPACE = mappingData["KEY_BACKSPACE"];
            this.KEY_SPACEBAR = mappingData["KEY_SPACEBAR"];
            this.KEY_ENTER = mappingData["KEY_ENTER"];
            this.KEY_UP = mappingData["KEY_UP"];
            this.KEY_DOWN = mappingData["KEY_DOWN"];
            this.KEY_LEFT = mappingData["KEY_LEFT"];
            this.KEY_RIGHT = mappingData["KEY_RIGHT"];
            this.KEY_TAB = mappingData["KEY_TAB"];
            this.KEY_INSERT = mappingData["KEY_INSERT"];
            this.KEY_DELETE = mappingData["KEY_DELETE"];
            this.KEY_HOME = mappingData["KEY_HOME"];
            this.KEY_END = mappingData["KEY_END"];
            this.KEY_PAGE_UP = mappingData["KEY_PAGE_UP"];
            this.KEY_PAGE_DOWN = mappingData["KEY_PAGE_DOWN"];
            this.KEY_SHIFT = mappingData["KEY_SHIFT"];
            this.KEY_CTRL = mappingData["KEY_CTRL"];
            this.KEY_ALT = mappingData["KEY_ALT"];
            this.KEY_ESCAPE = mappingData["KEY_ESCAPE"];
            this.KEY_TILDE = mappingData["KEY_TILDE"];
            this.KEY_QUOTE = mappingData["KEY_QUOTE"];
            this.KEY_SEMICOLON = mappingData["KEY_SEMICOLON"];
            this.KEY_COMMA = mappingData["KEY_COMMA"];
            this.KEY_PERIOD = mappingData["KEY_PERIOD"];
            this.KEY_SLASH = mappingData["KEY_SLASH"];
            this.KEY_BRACKET_LEFT = mappingData["KEY_BRACKET_LEFT"];
            this.KEY_BRACKET_RIGHT = mappingData["KEY_BRACKET_RIGHT"];
            this.KEY_BACKSLASH = mappingData["KEY_BACKSLASH"];
            this.KEY_RIGHT_ALT = mappingData["KEY_RIGHT_ALT"];
            this.KEY_RIGHT_CTRL = mappingData["KEY_RIGHT_CTRL"];
            this.KEY_RIGHT_SHIFT = mappingData["KEY_RIGHT_SHIFT"];
            this.KEY_NUMPAD_0 = mappingData["KEY_NUMPAD_0"];
            this.KEY_NUMPAD_1 = mappingData["KEY_NUMPAD_1"];
            this.KEY_NUMPAD_2 = mappingData["KEY_NUMPAD_2"];
            this.KEY_NUMPAD_3 = mappingData["KEY_NUMPAD_3"];
            this.KEY_NUMPAD_4 = mappingData["KEY_NUMPAD_4"];
            this.KEY_NUMPAD_5 = mappingData["KEY_NUMPAD_5"];
            this.KEY_NUMPAD_6 = mappingData["KEY_NUMPAD_6"];
            this.KEY_NUMPAD_7 = mappingData["KEY_NUMPAD_7"];
            this.KEY_NUMPAD_8 = mappingData["KEY_NUMPAD_8"];
            this.KEY_NUMPAD_9 = mappingData["KEY_NUMPAD_9"];
            this.KEY_NUMPAD_PERIOD = mappingData["KEY_NUMPAD_PERIOD"];
            this.KEY_NUMPAD_PLUS = mappingData["KEY_NUMPAD_PLUS"];
            this.KEY_NUMPAD_MINUS = mappingData["KEY_NUMPAD_MINUS"];
            this.KEY_NUMPAD_ENTER = mappingData["KEY_NUMPAD_ENTER"];
            this.KEY_F_1 = mappingData["KEY_F_1"];
            this.KEY_F_2 = mappingData["KEY_F_2"];
            this.KEY_F_3 = mappingData["KEY_F_3"];
            this.KEY_F_4 = mappingData["KEY_F_4"];
            this.KEY_F_5 = mappingData["KEY_F_5"];
            this.KEY_F_6 = mappingData["KEY_F_6"];
            this.KEY_F_7 = mappingData["KEY_F_7"];
            this.KEY_F_8 = mappingData["KEY_F_8"];
            this.KEY_F_9 = mappingData["KEY_F_9"];
            this.KEY_F_10 = mappingData["KEY_F_10"];
            this.KEY_F_11 = mappingData["KEY_F_11"];
            this.KEY_F_12 = mappingData["KEY_F_12"];
        }
    }
}
