using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

// autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.Emulators.RetroArch.Configuration.Internal
{
    /// <summary>
    ///     RetroAchievements is in beta.
    ///     Perhaps enable this in a future update
    /// </summary>
    [ConfigurationSection("cheevos", "Cheevos Options")]
    public partial interface AchievementConfiguration
    {
        [ConfigurationOption("cheevos_enable", false, DisplayName = "Enable RetroArchivements", Private = true)]
        bool CheevosEnable { get; set; }

        [ConfigurationOption("cheevos_hardcore_mode_enable", false,
            DisplayName = "Enable RetroArcheivements Hardcore Mode", Private = true)]
        bool CheevosHardcoreModeEnable { get; set; }

        [ConfigurationOption("cheevos_password", "", DisplayName = "RetroAchievements Password", Private = true)]
        string CheevosPassword { get; set; }

        [ConfigurationOption("cheevos_test_unofficial", false, DisplayName = "RetroAchievements Test", Private = true)]
        bool CheevosTestUnofficial { get; set; }

        [ConfigurationOption("cheevos_username", "", DisplayName = "RetroAchivements Username", Private = true)]
        string CheevosUsername { get; set; }
    }
}
