using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

// autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.Emulators.RetroArch.Configuration.Internal
{
    [ConfigurationSection("user", "User Options")]
    public interface UserConfiguration : IConfigurationSection<UserConfiguration>
    {
        // todo check max
        [ConfigurationOption("user_language", 0, DisplayName = "User Language", Private = true)]
        int UserLanguage { get; set; }
    }
}
