using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Snowflake.Tests;
using Newtonsoft.Json;
using Xunit;
namespace Snowflake.Emulator.Input.Tests
{
    public class KeyboardMappingTests
    {
        [Fact]
        public void KeyboardMapping_LoadTest()
        {
            string _mappings = TestUtilities.GetStringResource("Mapping.KeyboardMapping.json");
            var mappingData = JsonConvert.DeserializeObject<IDictionary<string, string>>(_mappings);
            var keyboardMapping = new KeyboardMapping(mappingData);
            Assert.NotNull(keyboardMapping);
        }

        [Theory]
        [InlineData("KEY_A")]
        [InlineData("KEY_B")]
        [InlineData("KEY_C")]
        [InlineData("KEY_D")]
        [InlineData("KEY_E")]
        [InlineData("KEY_F")]
        [InlineData("KEY_G")]
        [InlineData("KEY_H")]
        [InlineData("KEY_I")]
        [InlineData("KEY_J")]
        [InlineData("KEY_K")]
        [InlineData("KEY_L")]
        [InlineData("KEY_M")]
        [InlineData("KEY_N")]
        [InlineData("KEY_O")]
        [InlineData("KEY_P")]
        [InlineData("KEY_Q")]
        [InlineData("KEY_R")]
        [InlineData("KEY_S")]
        [InlineData("KEY_T")]
        [InlineData("KEY_U")]
        [InlineData("KEY_V")]
        [InlineData("KEY_W")]
        [InlineData("KEY_X")]
        [InlineData("KEY_Y")]
        [InlineData("KEY_Z")]
        [InlineData("KEY_0")]
        [InlineData("KEY_1")]
        [InlineData("KEY_2")]
        [InlineData("KEY_3")]
        [InlineData("KEY_4")]
        [InlineData("KEY_5")]
        [InlineData("KEY_6")]
        [InlineData("KEY_7")]
        [InlineData("KEY_8")]
        [InlineData("KEY_9")]
        [InlineData("KEY_EQUALS")]
        [InlineData("KEY_MINUS")]
        [InlineData("KEY_BACKSPACE")]
        [InlineData("KEY_SPACEBAR")]
        [InlineData("KEY_ENTER")]
        [InlineData("KEY_UP")]
        [InlineData("KEY_DOWN")]
        [InlineData("KEY_LEFT")]
        [InlineData("KEY_RIGHT")]
        [InlineData("KEY_TAB")]
        [InlineData("KEY_INSERT")]
        [InlineData("KEY_DELETE")]
        [InlineData("KEY_HOME")]
        [InlineData("KEY_END")]
        [InlineData("KEY_PAGE_UP")]
        [InlineData("KEY_PAGE_DOWN")]
        [InlineData("KEY_SHIFT")]
        [InlineData("KEY_CTRL")]
        [InlineData("KEY_ALT")]
        [InlineData("KEY_ESCAPE")]
        [InlineData("KEY_TILDE")]
        [InlineData("KEY_QUOTE")]
        [InlineData("KEY_SEMICOLON")]
        [InlineData("KEY_COMMA")]
        [InlineData("KEY_PERIOD")]
        [InlineData("KEY_SLASH")]
        [InlineData("KEY_BRACKET_LEFT")]
        [InlineData("KEY_BRACKET_RIGHT")]
        [InlineData("KEY_BACKSLASH")]
        [InlineData("KEY_RIGHT_ALT")]
        [InlineData("KEY_RIGHT_CTRL")]
        [InlineData("KEY_RIGHT_SHIFT")]
        [InlineData("KEY_NUMPAD_0")]
        [InlineData("KEY_NUMPAD_1")]
        [InlineData("KEY_NUMPAD_2")]
        [InlineData("KEY_NUMPAD_3")]
        [InlineData("KEY_NUMPAD_4")]
        [InlineData("KEY_NUMPAD_5")]
        [InlineData("KEY_NUMPAD_6")]
        [InlineData("KEY_NUMPAD_7")]
        [InlineData("KEY_NUMPAD_8")]
        [InlineData("KEY_NUMPAD_9")]
        [InlineData("KEY_NUMPAD_PERIOD")]
        [InlineData("KEY_NUMPAD_PLUS")]
        [InlineData("KEY_NUMPAD_MINUS")]
        [InlineData("KEY_NUMPAD_ENTER")]
        [InlineData("KEY_F_1")]
        [InlineData("KEY_F_2")]
        [InlineData("KEY_F_3")]
        [InlineData("KEY_F_4")]
        [InlineData("KEY_F_5")]
        [InlineData("KEY_F_6")]
        [InlineData("KEY_F_7")]
        [InlineData("KEY_F_8")]
        [InlineData("KEY_F_9")]
        [InlineData("KEY_F_10")]
        [InlineData("KEY_F_11")]
        [InlineData("KEY_F_12")]
        [InlineData("MOUSE_Y_DOWN")]
        [InlineData("MOUSE_Y_UP")]
        [InlineData("MOUSE_X_LEFT")]
        [InlineData("MOUSE_X_RIGHT")]
        [InlineData("MOUSE_LCLICK")]
        [InlineData("MOUSE_RCLICK")]
        [InlineData("MOUSE_MCLICK")]
        [InlineData("MOUSE_WHEELUP")]
        [InlineData("MOUSE_WHEELDOWN")]

        public void KeyboardMapping_EqualityTests(string mappingKey)
        {
            string _mappings = TestUtilities.GetStringResource("Mapping.KeyboardMapping.json");
            var mappingData = JsonConvert.DeserializeObject<IDictionary<string, string>>(_mappings);
            var keyboardMapping = new KeyboardMapping(mappingData);
            Assert.Equal(keyboardMapping[mappingKey], typeof(KeyboardMapping).GetProperty(mappingKey).GetValue(keyboardMapping));
        }

        [Theory]
        [InlineData("KEY_A")]
        [InlineData("KEY_B")]
        [InlineData("KEY_C")]
        [InlineData("KEY_D")]
        [InlineData("KEY_E")]
        [InlineData("KEY_F")]
        [InlineData("KEY_G")]
        [InlineData("KEY_H")]
        [InlineData("KEY_I")]
        [InlineData("KEY_J")]
        [InlineData("KEY_K")]
        [InlineData("KEY_L")]
        [InlineData("KEY_M")]
        [InlineData("KEY_N")]
        [InlineData("KEY_O")]
        [InlineData("KEY_P")]
        [InlineData("KEY_Q")]
        [InlineData("KEY_R")]
        [InlineData("KEY_S")]
        [InlineData("KEY_T")]
        [InlineData("KEY_U")]
        [InlineData("KEY_V")]
        [InlineData("KEY_W")]
        [InlineData("KEY_X")]
        [InlineData("KEY_Y")]
        [InlineData("KEY_Z")]
        [InlineData("KEY_0")]
        [InlineData("KEY_1")]
        [InlineData("KEY_2")]
        [InlineData("KEY_3")]
        [InlineData("KEY_4")]
        [InlineData("KEY_5")]
        [InlineData("KEY_6")]
        [InlineData("KEY_7")]
        [InlineData("KEY_8")]
        [InlineData("KEY_9")]
        [InlineData("KEY_EQUALS")]
        [InlineData("KEY_MINUS")]
        [InlineData("KEY_BACKSPACE")]
        [InlineData("KEY_SPACEBAR")]
        [InlineData("KEY_ENTER")]
        [InlineData("KEY_UP")]
        [InlineData("KEY_DOWN")]
        [InlineData("KEY_LEFT")]
        [InlineData("KEY_RIGHT")]
        [InlineData("KEY_TAB")]
        [InlineData("KEY_INSERT")]
        [InlineData("KEY_DELETE")]
        [InlineData("KEY_HOME")]
        [InlineData("KEY_END")]
        [InlineData("KEY_PAGE_UP")]
        [InlineData("KEY_PAGE_DOWN")]
        [InlineData("KEY_SHIFT")]
        [InlineData("KEY_CTRL")]
        [InlineData("KEY_ALT")]
        [InlineData("KEY_ESCAPE")]
        [InlineData("KEY_TILDE")]
        [InlineData("KEY_QUOTE")]
        [InlineData("KEY_SEMICOLON")]
        [InlineData("KEY_COMMA")]
        [InlineData("KEY_PERIOD")]
        [InlineData("KEY_SLASH")]
        [InlineData("KEY_BRACKET_LEFT")]
        [InlineData("KEY_BRACKET_RIGHT")]
        [InlineData("KEY_BACKSLASH")]
        [InlineData("KEY_RIGHT_ALT")]
        [InlineData("KEY_RIGHT_CTRL")]
        [InlineData("KEY_RIGHT_SHIFT")]
        [InlineData("KEY_NUMPAD_0")]
        [InlineData("KEY_NUMPAD_1")]
        [InlineData("KEY_NUMPAD_2")]
        [InlineData("KEY_NUMPAD_3")]
        [InlineData("KEY_NUMPAD_4")]
        [InlineData("KEY_NUMPAD_5")]
        [InlineData("KEY_NUMPAD_6")]
        [InlineData("KEY_NUMPAD_7")]
        [InlineData("KEY_NUMPAD_8")]
        [InlineData("KEY_NUMPAD_9")]
        [InlineData("KEY_NUMPAD_PERIOD")]
        [InlineData("KEY_NUMPAD_PLUS")]
        [InlineData("KEY_NUMPAD_MINUS")]
        [InlineData("KEY_NUMPAD_ENTER")]
        [InlineData("KEY_F_1")]
        [InlineData("KEY_F_2")]
        [InlineData("KEY_F_3")]
        [InlineData("KEY_F_4")]
        [InlineData("KEY_F_5")]
        [InlineData("KEY_F_6")]
        [InlineData("KEY_F_7")]
        [InlineData("KEY_F_8")]
        [InlineData("KEY_F_9")]
        [InlineData("KEY_F_10")]
        [InlineData("KEY_F_11")]
        [InlineData("KEY_F_12")]
        [InlineData("MOUSE_Y_DOWN")]
        [InlineData("MOUSE_Y_UP")]
        [InlineData("MOUSE_X_LEFT")]
        [InlineData("MOUSE_X_RIGHT")]
        [InlineData("MOUSE_LCLICK")]
        [InlineData("MOUSE_RCLICK")]
        [InlineData("MOUSE_MCLICK")]
        [InlineData("MOUSE_WHEELUP")]
        [InlineData("MOUSE_WHEELDOWN")]

        public void KeyboardMapping_IndexerTests(string mappingKey)
        {
            string _mappings = TestUtilities.GetStringResource("Mapping.KeyboardMapping.json");
            var mappingData = JsonConvert.DeserializeObject<IDictionary<string, string>>(_mappings);
            var keyboardMapping = new KeyboardMapping(mappingData);
            Assert.Equal(keyboardMapping[mappingKey], keyboardMapping[mappingKey]);
        }
    }
}
