using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
//going to disable recording for the time being
namespace Snowflake.Plugin.EmulatorAdapter.RetroArch.Configuration.Internal
{
    public class RecordConfiguration : ConfigurationSection
    {
        //this can be enum but the only other possible value is null.
        [ConfigurationOption("record_driver", DisplayName = "Record Driver", Private = true)]
        public string RecordDriver { get; set; } = "ffmpeg";

        [ConfigurationOption("auto_screenshot_filename", DisplayName = "Automatic screenshot filename", Private = true)]
        public bool AutoScreenshotFilename { get; set; } = true;

        [ConfigurationOption("video_gpu_record", DisplayName = "Enable Video Recording", Private = true)]
        public bool VideoGpuRecord { get; set; } = false;

        public RecordConfiguration() : base("record", "Record Options")
        {

        }

    }
}
