using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

// autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.Emulators.RetroArch.Configuration
{
    [ConfigurationSection("directory", "Directory Options")]
    public interface DirectoryConfiguration : IConfigurationSection<DirectoryConfiguration>
    {
        [ConfigurationOption("assets_directory", "default", PathType.Raw, DisplayName = "Assets Directory", 
            Private = true)]
        string AssetsDirectory { get; set; }

        [ConfigurationOption("audio_filter_dir", "default", PathType.Raw, DisplayName = "Audio Filter Dir", 
            Private = true)]
        string AudioFilterDir { get; set; }

        [ConfigurationOption("bundle_assets_dst_path", "", PathType.Raw, DisplayName = "Bundle Assets Dst Path", 
            Private = true)]
        string BundleAssetsDstPath { get; set; }

        [ConfigurationOption("bundle_assets_dst_path_subdir", "", PathType.Raw, DisplayName = "Bundle Assets Dst Path Subdir",
             Private = true)]
        string BundleAssetsDstPathSubdir { get; set; }

        [ConfigurationOption("bundle_assets_src_path", "", PathType.Raw, DisplayName = "Bundle Assets Src Path", 
            Private = true)]
        string BundleAssetsSrcPath { get; set; }

        [ConfigurationOption("cache_directory", "", PathType.Raw, DisplayName = "Cache Directory",  Private = true)]
        string CacheDirectory { get; set; }

        [ConfigurationOption("cheat_database_path", "", PathType.Raw, DisplayName = "Cheat Database Path", 
            Private = true)]
        string CheatDatabasePath { get; set; }

        [ConfigurationOption("content_database_path", "", PathType.Raw, DisplayName = "Content Database Path", 
            Private = true)]
        string ContentDatabasePath { get; set; }

        [ConfigurationOption("content_history_dir", "", PathType.Raw, DisplayName = "Content History Dir", 
            Private = true)]
        string ContentHistoryDir { get; set; }

        [ConfigurationOption("content_history_path", ":\\content_history.lpl", PathType.Raw, DisplayName = "Content History Path",
             Private = true)]
        string ContentHistoryPath { get; set; }

        [ConfigurationOption("core_assets_directory", "default", PathType.Raw, DisplayName = "Core Assets Directory", 
            Private = true)]
        string CoreAssetsDirectory { get; set; }

        [ConfigurationOption("core_options_path", "", PathType.Raw, DisplayName = "Core Options Path",  Private = true)]
        string CoreOptionsPath { get; set; }

        [ConfigurationOption("cursor_directory", "", PathType.Raw, DisplayName = "Cursor Directory",  Private = true)]
        string CursorDirectory { get; set; }

        [ConfigurationOption("dynamic_wallpapers_directory", "default", PathType.Raw, DisplayName = "Dynamic Wallpapers Directory",
             Private = true)]
        string DynamicWallpapersDirectory { get; set; }

        [ConfigurationOption("input_remapping_directory", "", PathType.Raw, DisplayName = "Input Remapping Directory", 
            Private = true)]
        string InputRemappingDirectory { get; set; }

        [ConfigurationOption("joypad_autoconfig_dir", "", PathType.Raw, DisplayName = "Joypad Autoconfig Dir", 
            Private = true)]
        string JoypadAutoconfigDir { get; set; }

        [ConfigurationOption("libretro_directory", "", PathType.Raw, DisplayName = "Libretro Directory", 
            Private = true)]
        string LibretroDirectory { get; set; }

        [ConfigurationOption("libretro_info_path", "", PathType.Raw, DisplayName = "Libretro Info Path", 
            Private = true)]
        string LibretroInfoPath { get; set; }

        [ConfigurationOption("osk_overlay_directory", "default", PathType.Raw, DisplayName = "Osk Overlay Directory", 
            Private = true)]
        string OskOverlayDirectory { get; set; }

        [ConfigurationOption("overlay_directory", "default", PathType.Raw, DisplayName = "Overlay Directory", 
            Private = true)]
        string OverlayDirectory { get; set; }

        [ConfigurationOption("playlist_directory",  "default", PathType.Raw, DisplayName = "Playlist Directory", 
            Private = true)]
        string PlaylistDirectory { get; set; }

        [ConfigurationOption("recording_config_directory", "", PathType.Raw, DisplayName = "Recording Config Directory",
            
            Private = true)]
        string RecordingConfigDirectory { get; set; }

        [ConfigurationOption("recording_output_directory", "", PathType.Raw, DisplayName = "Recording Output Directory",
            
            Private = true)]
        string RecordingOutputDirectory { get; set; }

        [ConfigurationOption("resampler_directory", "", PathType.Raw, DisplayName = "Resampler Directory", 
            Private = true)]
        string ResamplerDirectory { get; set; }

        [ConfigurationOption("rgui_browser_directory", "default", PathType.Raw, DisplayName = "Rgui Browser Directory", 
            Private = true)]
        string RguiBrowserDirectory { get; set; }

        [ConfigurationOption("rgui_config_directory", "default", PathType.Raw, DisplayName = "Rgui Config Directory", 
            Private = true)]
        string RguiConfigDirectory { get; set; }

        [ConfigurationOption("screenshot_directory", "default", PathType.Raw, DisplayName = "Screenshot Directory", 
            Private = true)]
        string ScreenshotDirectory { get; set; }

        [ConfigurationOption("system_directory", "default", PathType.Raw, DisplayName = "System Directory", 
            Private = true)]
        string SystemDirectory { get; set; }

        [ConfigurationOption("savefile_directory", "default", PathType.Raw, DisplayName = "Savefile Directory")]
        string SavefileDirectory { get; set; }

        [ConfigurationOption("thumbnails_directory", "default", PathType.Raw, DisplayName = "Thumbnails Directory", 
            Private = true)]
        string ThumbnailsDirectory { get; set; }

        [ConfigurationOption("video_filter_dir", "default", PathType.Raw, DisplayName = "Video Filter Dir", 
            Private = true)]
        string VideoFilterDir { get; set; }

        [ConfigurationOption("video_font_path", "", PathType.Raw, DisplayName = "Video Font Path",  Private = true)]
        string VideoFontPath { get; set; }

        [ConfigurationOption("video_shader_dir", "default", PathType.Raw, DisplayName = "Video Shader Dir", 
            Private = true)]
        string VideoShaderDir { get; set; }

        [ConfigurationOption("savestate_directory", "default", PathType.Raw, DisplayName = "Savestate Directory", 
            Private = true)]
        string SavestateDirectory { get; set; }
    }
}
