export const landscapeCover = 'https://upload.wikimedia.org/wikipedia/en/3/32/Super_Mario_World_Coverart.png'
export const portraitCover = 'http://vignette2.wikia.nocookie.net/mario/images/6/60/SMBBoxart.png/revision/latest?cb=20120609143443'
export const publisher = 'Nintendo'
export const title = 'Super Mario Bros'
export const description = 'Super Mario World, subtitled Super Mario Bros. 4 for its original Japanese release, is a 1990 platform video game developed and published by Nintendo for the Super Nintendo Entertainment System (Super NES).'
