using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py

namespace Snowflake.Plugin.Emulators.RetroArch.Configuration.Internal
{
    [ConfigurationSection("network", "Network Options")]
    public interface NetworkConfiguration : IConfigurationSection<NetworkConfiguration>
    {
        [ConfigurationOption("network_cmd_enable", true, DisplayName = "Network Cmd Enable", Private = true)]
        bool NetworkCmdEnable { get; set; }

        [ConfigurationOption("network_cmd_port", 55355, DisplayName = "Network Cmd Port", Private = true)]
        int NetworkCmdPort { get; set; }

        [ConfigurationOption("network_remote_base_port", 55400, DisplayName = "Network Remote Base Port", Private = true
            )]
        int NetworkRemoteBasePort { get; set; }

        [ConfigurationOption("network_remote_enable", true, DisplayName = "Enable Network Remoting", Private = true)]
        bool NetworkRemoteEnable { get; set; }

        [ConfigurationOption("network_remote_enable_user_p1", false, DisplayName = "Network Remote Enable User P1",
            Private = true)]
        bool NetworkRemoteEnableUserP1 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p10", false, DisplayName = "Network Remote Enable User P10",
            Private = true)]
        bool NetworkRemoteEnableUserP10 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p11", false, DisplayName = "Network Remote Enable User P11",
            Private = true)]
        bool NetworkRemoteEnableUserP11 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p12", false, DisplayName = "Network Remote Enable User P12",
            Private = true)]
        bool NetworkRemoteEnableUserP12 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p13", false, DisplayName = "Network Remote Enable User P13",
            Private = true)]
        bool NetworkRemoteEnableUserP13 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p14", false, DisplayName = "Network Remote Enable User P14",
            Private = true)]
        bool NetworkRemoteEnableUserP14 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p15", false, DisplayName = "Network Remote Enable User P15",
            Private = true)]
        bool NetworkRemoteEnableUserP15 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p16", false, DisplayName = "Network Remote Enable User P16",
            Private = true)]
        bool NetworkRemoteEnableUserP16 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p2", false, DisplayName = "Network Remote Enable User P2",
            Private = true)]
        bool NetworkRemoteEnableUserP2 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p3", false, DisplayName = "Network Remote Enable User P3",
            Private = true)]
        bool NetworkRemoteEnableUserP3 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p4", false, DisplayName = "Network Remote Enable User P4",
            Private = true)]
        bool NetworkRemoteEnableUserP4 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p5", false, DisplayName = "Network Remote Enable User P5",
            Private = true)]
        bool NetworkRemoteEnableUserP5 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p6", false, DisplayName = "Network Remote Enable User P6",
            Private = true)]
        bool NetworkRemoteEnableUserP6 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p7", false, DisplayName = "Network Remote Enable User P7",
            Private = true)]
        bool NetworkRemoteEnableUserP7 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p8", false, DisplayName = "Network Remote Enable User P8",
            Private = true)]
        bool NetworkRemoteEnableUserP8 { get; set; }

        [ConfigurationOption("network_remote_enable_user_p9", false, DisplayName = "Network Remote Enable User P9",
            Private = true)]
        bool NetworkRemoteEnableUserP9 { get; set; }
    }
}