using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py

namespace Snowflake.Plugin.EmulatorAdapter.RetroArch.Configuration.Internal
{
    [ConfigurationSection("threaded", "Threaded Options")]
    public interface ThreadedConfiguration : IConfigurationSection<ThreadedConfiguration>
    {
        //this probably shouldn't be touched
        [ConfigurationOption("threaded_data_runloop_enable", true, DisplayName = "Threaded Data Runloop Enable",
            Private = false)]
        bool ThreadedDataRunloopEnable { get; set; }
    }
}