using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal
{
    /// <summary>
    /// Used internally by Retroarch GUI
    /// Since we wrap this, we don't care about this.
    /// </summary>
    public class BundleConfiguration : ConfigurationSection
    {
        [ConfigurationOption("bundle_assets_extract_enable", DisplayName = "Bundle Assets Extract Enable", Private = true)]
        public bool BundleAssetsExtractEnable { get; set; } = false;

        [ConfigurationOption("bundle_assets_extract_last_version", DisplayName = "Bundle Assets Extract Last Version", Private = true)]
        public int BundleAssetsExtractLastVersion { get; set; } = 0;

        [ConfigurationOption("bundle_assets_extract_version_current", DisplayName = "Bundle Assets Extract Version Current", Private = true)]
        public int BundleAssetsExtractVersionCurrent { get; set; } = 0;

        public BundleConfiguration() : base("bundle", "Bundle Options")
        {

        }

    }
}
