using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal
{
    /// <summary>
    /// Not applicable on Desktop OS
    /// </summary>
    public class CameraConfiguration : ConfigurationSection
    {
        [ConfigurationOption("camera_allow", DisplayName = "Camera Allow", Private = true)]
        public bool CameraAllow { get; set; } = false;

        [ConfigurationOption("camera_device", DisplayName = "Camera Device", Private = true)]
        public string CameraDevice { get; set; } = "";

        //this is enum but null is th eonly possible value 
        [ConfigurationOption("camera_driver", DisplayName = "Camera Driver", Private = true)]
        public string CameraDriver { get; set; } = "null";

        public CameraConfiguration() : base("camera", "Camera Options")
        {

        }

    }
}
