using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal
{
    /// <summary>
    /// Have no discernable effect on Windows and are disabled immediately
    /// (XBOX Only Setting?)
    /// </summary>
    public class FilterConfiguration : ConfigurationSection
    {
        [ConfigurationOption("flicker_filter_enable", DisplayName = "Flicker Filter Enable", Private = true)]
        public bool FlickerFilterEnable { get; set; } = false;
        //todo check max
        [ConfigurationOption("flicker_filter_index", DisplayName = "Flicker Filter Index", Private = true)]
        public int FlickerFilterIndex { get; set; } = 0;
        [ConfigurationOption("soft_filter_enable", DisplayName = "Soft Filter Enable", Private = true)]
        public bool SoftFilterEnable { get; set; } = false;
        //todo check max
        [ConfigurationOption("soft_filter_index", DisplayName = "Soft Filter Index", Private = true)]
        public int SoftFilterIndex { get; set; } = 0;
        public FilterConfiguration() : base("flicker", "Filter Options", "retroarch.cfg")
        {

        }

    }
}
