using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal
{
    public class NetworkConfiguration : ConfigurationSection
    {
        [ConfigurationOption("network_cmd_enable", DisplayName = "Network Cmd Enable", Private = true)]
        public bool NetworkCmdEnable { get; set; } = true;

        [ConfigurationOption("network_cmd_port", DisplayName = "Network Cmd Port", Private = true)]
        public int NetworkCmdPort { get; set; } = 55355;

        [ConfigurationOption("network_remote_base_port", DisplayName = "Network Remote Base Port", Private = true)]
        public int NetworkRemoteBasePort { get; set; } = 55400;

        [ConfigurationOption("network_remote_enable", DisplayName = "Enable Network Remoting", Private = true)]
        public bool NetworkRemoteEnable { get; set; } = true;

        [ConfigurationOption("network_remote_enable_user_p1", DisplayName = "Network Remote Enable User P1", Private = true)]
        public bool NetworkRemoteEnableUserP1 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p10", DisplayName = "Network Remote Enable User P10", Private = true)]
        public bool NetworkRemoteEnableUserP10 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p11", DisplayName = "Network Remote Enable User P11", Private = true)]
        public bool NetworkRemoteEnableUserP11 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p12", DisplayName = "Network Remote Enable User P12", Private = true)]
        public bool NetworkRemoteEnableUserP12 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p13", DisplayName = "Network Remote Enable User P13", Private = true)]
        public bool NetworkRemoteEnableUserP13 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p14", DisplayName = "Network Remote Enable User P14", Private = true)]
        public bool NetworkRemoteEnableUserP14 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p15", DisplayName = "Network Remote Enable User P15", Private = true)]
        public bool NetworkRemoteEnableUserP15 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p16", DisplayName = "Network Remote Enable User P16", Private = true)]
        public bool NetworkRemoteEnableUserP16 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p2", DisplayName = "Network Remote Enable User P2", Private = true)]
        public bool NetworkRemoteEnableUserP2 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p3", DisplayName = "Network Remote Enable User P3", Private = true)]
        public bool NetworkRemoteEnableUserP3 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p4", DisplayName = "Network Remote Enable User P4", Private = true)]
        public bool NetworkRemoteEnableUserP4 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p5", DisplayName = "Network Remote Enable User P5", Private = true)]
        public bool NetworkRemoteEnableUserP5 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p6", DisplayName = "Network Remote Enable User P6", Private = true)]
        public bool NetworkRemoteEnableUserP6 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p7", DisplayName = "Network Remote Enable User P7", Private = true)]
        public bool NetworkRemoteEnableUserP7 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p8", DisplayName = "Network Remote Enable User P8", Private = true)]
        public bool NetworkRemoteEnableUserP8 { get; set; } = false;
        [ConfigurationOption("network_remote_enable_user_p9", DisplayName = "Network Remote Enable User P9", Private = true)]
        public bool NetworkRemoteEnableUserP9 { get; set; } = false;

        public NetworkConfiguration() : base("network", "Network Options")
        {

        }

    }
}
