using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal
{
    public class RewindConfiguration : ConfigurationSection
    {
        [ConfigurationOption("rewind_enable", DisplayName = "Enable Rewind", Private = true)]
        public bool RewindEnable { get; set; } = false;

        [ConfigurationOption("rewind_granularity", DisplayName = "Rewind Granularity", Private = true)]
        public int RewindGranularity { get; set; } = 1;

        public RewindConfiguration() : base("rewind", "Rewind Options", "retroarch.cfg")
        {

        }

    }
}
