using Snowflake.Configuration;
using Snowflake.Configuration.Attributes;

//autogenerated using generate_retroarch.py
namespace Snowflake.Plugin.EmulatorHandler.RetroArch.Configuration.Internal
{
    public class UiConfiguration : ConfigurationSection
    {
       [ConfigurationOption("ui_companion_enable", DisplayName = "Ui Companion Enable")]
       public bool UiCompanionEnable { get; set; } = false;
       [ConfigurationOption("ui_companion_start_on_boot", DisplayName = "Ui Companion Start On Boot")]
       public bool UiCompanionStartOnBoot { get; set; } = true;
       [ConfigurationOption("ui_menubar_enable", DisplayName = "Ui Menubar Enable")]
       public bool UiMenubarEnable { get; set; } = false;

       public UiConfiguration() : base ("ui", "UI Options", "retroarch.cfg")
       {

       }
       
     }
}
